bugfix/ CORE-238 nested secrets
OpenSesame/core-build-library pull request #9
Opened 2021-04-13 21:23 UTC by kbajno

If an AWS secret key value is a nested JSON object, the value would not get templated properly in the output file. We need to stringify the response if it is JSON so it gets properly written and then set in the file.

2021-04-13 21:55 UTC, marclitchfield requested changes

2021-04-13 21:55 UTC, marclitchfield commented on src/commands/eval-tpl.js
> +        return stringifyJSON(value);
Does this still work if the value is a string, or does it double-up the double quotes? 
I think what we want to do is check if it is an object, and then do a JSON.stringify (instead of try/catch).

2021-04-13 21:56 UTC, marclitchfield commented on src/commands/eval-tpl.js
> +        return stringifyJSON(value);
I think the check would be `typeof yourVariable === 'object' && yourVariable !== null`

2021-04-14 20:46 UTC, kbajno commented on src/commands/eval-tpl.js
> +        return stringifyJSON(value);
It does add quotes to the string that then get read into a file. Isn't an issue if you're using it for an env file, but might be an issue if you're templating something else! I like the object check idea. I updated the code if you could give it another look!

2021-04-14 20:55 UTC, marclitchfield approved these changes

2021-04-14 21:04 UTC, merged